/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeelRouteImport } from './routes/feel'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ArriveRouteImport } from './routes/arrive'
import { Route as IndexRouteImport } from './routes/index'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeelRoute = FeelRouteImport.update({
  id: '/feel',
  path: '/feel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ArriveRoute = ArriveRouteImport.update({
  id: '/arrive',
  path: '/arrive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrive': typeof ArriveRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/feel': typeof FeelRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/upgrade': typeof UpgradeRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrive': typeof ArriveRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/feel': typeof FeelRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/upgrade': typeof UpgradeRoute
  '/work': typeof WorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrive': typeof ArriveRoute
  '/connect': typeof ConnectRoute
  '/dashboard': typeof DashboardRoute
  '/feel': typeof FeelRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/onboarding': typeof OnboardingRoute
  '/upgrade': typeof UpgradeRoute
  '/work': typeof WorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrive'
    | '/connect'
    | '/dashboard'
    | '/feel'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/upgrade'
    | '/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrive'
    | '/connect'
    | '/dashboard'
    | '/feel'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/upgrade'
    | '/work'
  id:
    | '__root__'
    | '/'
    | '/arrive'
    | '/connect'
    | '/dashboard'
    | '/feel'
    | '/login'
    | '/me'
    | '/onboarding'
    | '/upgrade'
    | '/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArriveRoute: typeof ArriveRoute
  ConnectRoute: typeof ConnectRoute
  DashboardRoute: typeof DashboardRoute
  FeelRoute: typeof FeelRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  OnboardingRoute: typeof OnboardingRoute
  UpgradeRoute: typeof UpgradeRoute
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feel': {
      id: '/feel'
      path: '/feel'
      fullPath: '/feel'
      preLoaderRoute: typeof FeelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrive': {
      id: '/arrive'
      path: '/arrive'
      fullPath: '/arrive'
      preLoaderRoute: typeof ArriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArriveRoute: ArriveRoute,
  ConnectRoute: ConnectRoute,
  DashboardRoute: DashboardRoute,
  FeelRoute: FeelRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  OnboardingRoute: OnboardingRoute,
  UpgradeRoute: UpgradeRoute,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
